### ISSUE TITLE
Regression between 1.1.0 and 1.2.0 (and up to 1.3.2)

### ISSUE THREAD

**Issue by 1000i100** [arlac77/browser-ava#236]
Something there : https://github.com/arlac77/browser-ava/compare/v1.1.0...v1.2.0
Make Firefox run slower.
As a consequence, this test was passing and now fail : 

```js
import test from 'ava';

async function timeTrack(arrayFuncAndParams,timeout){
	return Promise.race([
		new Promise(resolve => setTimeout(
				()=>resolve({ms:timeout,params:arrayFuncAndParams,timeout:true}),
				timeout
			)),
		new Promise(async resolve=>{
			const startTime = Date.now();
			const func = arrayFuncAndParams[0];
			const params = arrayFuncAndParams.slice(1);

			const res = await func(...params);
			const endTime = Date.now();
			const elapsed = endTime - startTime;
			resolve({ms:elapsed,params:arrayFuncAndParams,result:res});
		})]
	);
}

test('pingTracker give time elapsed', async t => {
	await sleep(1); // in some test environnement this fix latency bug.
	const mockedFunc = async (first,second)=>{await sleep(second);return first};
	const firstParameter = 'finalResult';
	const secondParameter = 11;
	const toCall = [mockedFunc,firstParameter,secondParameter];
	const timeout = 1000;
	const result = await timeTrack(toCall,timeout);
	t.is(result.result,firstParameter);
	t.is(result.params[1],firstParameter);
	t.regex(result.ms.toString(),/1[0-9]/);
});
```
PS : I run it with `browser-ava **.test.mjs --chromium --firefox`

**Comment by arlac77** [comment]
that is to keep the cli informed about the progress.
Is it a timing issue ?
There are also some values wich cant be converted into json (Symbols, Functions, ...)

**Comment by 1000i100** [comment]
Yes, it's a timing issue : 
In my test case, there is a sleep for 11ms and the timeTrack function must return the timing (or near it : i allow up to 19ms with my regex) but with firefox, since version 1.2.0, it's near 40ms.
I've tested to put the line 176 in a setTimeout(line176, 0ms) and it lower the timing some time enough to pass the test, some time around 25ms.

I understand your goal about updating the result, but i don't understand why it slow down the test. The reporting time should be between test, not during it.

**Comment by 1000i100** [comment]
With 1.3.13 it looks to be fixed.
